# Security SETUP
security:

    encoders:
        AppBundle\Entity\User: bcrypt
    role_hierarchy:
        ROLE_ADMIN: [ROLE_ALLOWED_TO_SWITCH]
        ROLE_BUYER_ADMIN: [ROLE_BUYER]
        ROLE_GROWER_ADMIN: [ROLE_GROWER]
        ROLE_BREEDER_ADMIN: [ROLE_BREEDER]
        ROLE_AGENT_ADMIN: [ROLE_AGENT]
        ROLE_BUYER_MAIN: [ROLE_ADMIN_BUYER]
        ROLE_GROWER_MAIN: [ROLE_ADMIN_GROWER]
        ROLE_BREEDER_MAIN: [ROLE_ADMIN_BREEDER]
        ROLE_AGENT_MAIN: [ROLE_ADMIN_AGENT]
    # User Provider
    providers:
        our_users:
            entity: { class: AppBundle\Entity\User, property: email }

    firewalls:
        # disables authentication for assets and the profiler
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        login:
            pattern: ^/api/login
            stateless: true
            anonymous: true
        api:
            pattern: ^/api
            stateless: true
            guard:
                authenticators:
                    - app.jwt_token_authenticator
        main:
            anonymous: ~
            guard:
                authenticators:
                    - app.security.login_form_authenticator
            logout:
                 path: /logout

            switch_user: ~

    access_control:
        # - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/api/login,   roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api,         roles: IS_AUTHENTICATED_FULLY }
